from _typeshed import Incomplete

class Power_divergenceResult: ...

def power_divergence(f_obs, f_exp: Incomplete | None = ..., ddof: int = ..., lambda_: Incomplete | None = ...): ...
def chisquare(f_obs, f_exp: Incomplete | None = ..., ddof: int = ...): ...
