paths:                # files or directories to analyze
  - arkouda
exclude: .*/tests     # regex to skip test files
skip_magic: True      # ignore __dunder__ methods (except __init__)
skip_init: True       # ignore __init__ methods
skip_private: True    # ignore names starting with _
fail_under: 76.0        # exit non-zero if coverage < 76%
badge: docs/badge.svg # generate an SVG badge

