repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2       # ← pick the latest
    hooks:
      # 1) your lint hook (optional -- you already have this)
      - id: ruff
        args: 
          - --fix        # applies lint‐rule fixes in place
          - --extend-ignore=E712,E741,PTH110,PTH118,PTH108,C403,PTH100,PTH109,F841,F401,W291,W293,PT012,D400,PLR2044,B034,PT011,RUF034,N812,D404,PTH202,PLC0206,RUF013,PTH208,PT021,B015,C404,PT006,RUF040,PT017,B011,PT015,PT022,SIM222,SIM210,PT014,SIM113,C414,PLR1730,PLR0124,C405,SIM117,B023,SIM105,PLW1508,PTH103,B018,B008,PTH107,PLW1510,RET502,F821,E721,E731,PT007,PT003
        exclude: ^(tests/deprecated)

      # 2) the formatter hook
      - id: ruff-format
        files: '\.py$'         # make sure it only hits .py files

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2        # or whatever the latest isort version is
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile=black"]
        exclude: ^(tests/deprecated)
