[pytest]

# pytest configuration file for tests/optioned-server

filterwarnings =
    ignore:Version mismatch between client .*

testpaths =
    tests/optioned-server/t1.py

#norecursedirs =
#    .git

python_functions =
    test_*

# env =
# markers =
