"""
Compat shim for building Arkouda with Versioneer (v0.19).

This `setup.py` file is intentionally minimal. It exists only to provide
setuptools with the version and custom command classes required by the
vendored Versioneer installation. In particular:

- `pyproject.toml` holds the main project metadata (name, description,
  dependencies, etc.).
- `setup.cfg` contains the `[versioneer]` configuration block required
  by Versioneer 0.19.
- `arkouda/_version.py` is generated by `versioneer.py setup` and is used
  at runtime to compute or embed the package version.

This shim ensures that PEP-517/518 isolated builds can still succeed by
exposing:
  * `versioneer.get_version()`  → dynamic version string from Git tags
  * `versioneer.get_cmdclass()` → custom setuptools commands for sdist/wheel

No other build configuration should be added here. For new settings,
prefer `pyproject.toml`.
"""

# setup.py (compat shim for Versioneer 0.19)
from setuptools import setup

import versioneer

setup(
    name="arkouda",
    version=versioneer.get_version(),
    cmdclass=versioneer.get_cmdclass(),
)
