#!/usr/bin/env python3

"""
Run check.py, automatically starting/stopping the server.
"""

import logging
import sys

from server_util import *
from server_util.test.server_test_util import get_arkouda_numlocales, start_arkouda_server

logging.basicConfig(level=logging.INFO)

start_arkouda_server(get_arkouda_numlocales())
ret = run_client_live(os.path.join(get_arkouda_home(), "tests", "check.py"))
stop_arkouda_server()
print("{} running checks".format("Error" if ret else "Success"))
sys.exit(ret)
