name: build-CI-container-jobs
on:
  push:
    branches: [ main ]
    # This limits the action so it only builds when this file changes
    paths:
      - docker/ubuntu-with-arkouda-deps/Dockerfile
      - docker/almalinux-with-arkouda-deps/Dockerfile
      # also trigger on changes to this workflow file itself
      - .github/workflows/build-CI-container.yml
      - .github/workflows/build-CI-container-jobs.yml
  pull_request:
    paths:
      # same as for pushes above
      - docker/ubuntu-with-arkouda-deps/Dockerfile
      - docker/almalinux-with-arkouda-deps/Dockerfile
      - .github/workflows/build-CI-container.yml
      - .github/workflows/build-CI-container-jobs.yml
  # Adds a "manual run" option in the GH UI
  workflow_dispatch:

jobs:
  build-ubuntu-with-arkouda-deps-200:
    uses: ./.github/workflows/build-CI-container.yml
    with:
      DOCKERFILE: docker/ubuntu-with-arkouda-deps/Dockerfile
      IMAGE_NAME: ubuntu-with-arkouda-deps-chpl-2.0.0
      CONTEXTPATH: docker/ubuntu-with-arkouda-deps
      CHPL_VERSION: 2.0.0
  build-ubuntu-with-arkouda-deps-210:
    uses: ./.github/workflows/build-CI-container.yml
    with:
      DOCKERFILE: docker/ubuntu-with-arkouda-deps/Dockerfile
      IMAGE_NAME: ubuntu-with-arkouda-deps-chpl-2.1.0
      CONTEXTPATH: docker/ubuntu-with-arkouda-deps
      CHPL_VERSION: 2.1.0
  build-ubuntu-with-arkouda-deps-220:
    uses: ./.github/workflows/build-CI-container.yml
    with:
      DOCKERFILE: docker/ubuntu-with-arkouda-deps/Dockerfile
      IMAGE_NAME: ubuntu-with-arkouda-deps-chpl-2.2.0
      CONTEXTPATH: docker/ubuntu-with-arkouda-deps
      CHPL_VERSION: 2.2.0
  build-ubuntu-with-arkouda-deps-230:
    uses: ./.github/workflows/build-CI-container.yml
    with:
      DOCKERFILE: docker/ubuntu-with-arkouda-deps/Dockerfile
      IMAGE_NAME: ubuntu-with-arkouda-deps-chpl-2.3.0
      CONTEXTPATH: docker/ubuntu-with-arkouda-deps
      CHPL_VERSION: 2.3.0
  build-ubuntu-with-arkouda-deps-240:
    uses: ./.github/workflows/build-CI-container.yml
    with:
      DOCKERFILE: docker/ubuntu-with-arkouda-deps/Dockerfile
      IMAGE_NAME: ubuntu-with-arkouda-deps-chpl-2.4.0
      CONTEXTPATH: docker/ubuntu-with-arkouda-deps
      CHPL_VERSION: 2.4.0
  build-ubuntu-with-arkouda-deps-250:
    uses: ./.github/workflows/build-CI-container.yml
    with:
      DOCKERFILE: docker/ubuntu-with-arkouda-deps/Dockerfile
      IMAGE_NAME: ubuntu-with-arkouda-deps-chpl-2.5.0
      CONTEXTPATH: docker/ubuntu-with-arkouda-deps
      CHPL_VERSION: 2.5.0
  build-almalinux-with-arkouda-deps:
    uses: ./.github/workflows/build-CI-container.yml
    with:
      DOCKERFILE: docker/almalinux-with-arkouda-deps/Dockerfile
      IMAGE_NAME: almalinux-with-arkouda-deps
      CONTEXTPATH: docker/almalinux-with-arkouda-deps
