name: CI

on: [pull_request, merge_group, workflow_dispatch]

env:
  ARKOUDA_QUICK_COMPILE: true

jobs:
  arkouda_python_portability:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ['3.12']
    container:
      image: chapel/chapel:2.3.0
    steps:
    - uses: actions/checkout@v3  
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{matrix.python-version}}
    - name: Check python version
      run: |
        python3 --version

